import type { Part } from './types';

export const parts: Part[] = [
	{
		id: '1',
		name: 'JDM Honda K24A Engine RBB 06-08 Acura TSX',
		price: 1649,
		category: 'Engine',
		condition: 'Excellent',
		model: 'Acura TSX',
		year: '2006-2008',
		mileage: 65000,
		shortDescription: 'K24A2 3 Lobe VTEC engine, complete',
		fullDescription: 'JDM Honda K24A engine from 2006-2008 Acura TSX. RBB engine code. Complete with all accessories, intake manifold, and throttle body. 3-lobe VTEC system. Compression tested and verified. Clean engine bay pull with no leaks. Perfect for K-swap builds.',
		tags: ['k-series', 'vtec', 'tsx', 'engine', 'k24', 'acura'],
		image: '/k24.png'
	},
	{
		id: '2',
		name: 'JDM Honda K24A Engine RBB 04-08 Acura TSX',
		price: 1649,
		category: 'Engine',
		condition: 'Excellent',
		model: 'Acura TSX',
		year: '2004-2008',
		mileage: 58000,
		shortDescription: 'K24A2 3 Lobe VTEC, low mileage',
		fullDescription: 'JDM K24A engine with RBB code from Acura TSX. Features 3-lobe VTEC for excellent mid-range power. Includes all sensors, coil packs, and intake manifold. Tested and running strong. Popular choice for Civic and Integra swaps. No modifications needed.',
		tags: ['k-series', 'vtec', 'tsx', 'engine', 'k24', 'acura'],
		image: ''
	},
	{
		id: '3',
		name: 'JDM 99-01 Honda B20B 2.0L DOHC High Compression Engine',
		price: 1449,
		category: 'Engine',
		condition: 'Good',
		model: 'CR-V',
		year: '1999-2001',
		mileage: 72000,
		shortDescription: 'B20B high compression DOHC engine',
		fullDescription: 'JDM Honda B20B 2.0L DOHC engine from CR-V. High compression variant with excellent torque. Complete longblock with intake manifold and accessories. Popular for LS/VTEC builds when paired with VTEC head. Clean compression test results. Minor valve cover gasket seepage.',
		tags: ['b-series', 'b20', 'crv', 'engine', 'dohc'],
		image: ''
	},
	{
		id: '4',
		name: '2001-2005 Honda Civic Engine D17A VTEC EX',
		price: 1799,
		category: 'Engine',
		condition: 'Excellent',
		model: 'Civic',
		year: '2001-2005',
		mileage: 48000,
		shortDescription: 'D17A VTEC 1.7L, low miles',
		fullDescription: 'Honda Civic D17A VTEC engine from 2001-2005 EX model. 1.7L SOHC VTEC with excellent fuel economy and reliability. Includes all sensors, alternator, and power steering pump. Very low mileage for the year. Perfect replacement or swap candidate. Runs smooth and quiet.',
		tags: ['d-series', 'vtec', 'civic', 'engine', 'd17', 'sohc'],
		image: ''
	},
	{
		id: '5',
		name: 'JDM Honda K24A Engine 2003-2007 Accord Element',
		price: 1699,
		category: 'Engine',
		condition: 'Good',
		model: 'Accord',
		year: '2003-2007',
		mileage: 82000,
		shortDescription: 'K24A 2.4L RAA engine code',
		fullDescription: 'JDM K24A engine from Honda Accord/Element. RAA engine code. 2.4L i-VTEC with great power and torque characteristics. Complete with intake manifold, throttle body, and all accessories. Ideal for K-swap projects. Compression tested with good results across all cylinders.',
		tags: ['k-series', 'vtec', 'accord', 'element', 'engine', 'k24'],
		image: ''
	},
	{
		id: '6',
		name: '2006-2008 Honda Ridgeline Pilot Engine J35A',
		price: 2149,
		category: 'Engine',
		condition: 'Excellent',
		model: 'Ridgeline/Pilot',
		year: '2006-2008',
		mileage: 55000,
		shortDescription: 'J35A 3.5L AWD 4X4 JDM engine',
		fullDescription: 'Honda J35A 3.5L V6 engine from Ridgeline/Pilot. AWD compatible with all accessories included. VTEC on both banks for excellent power delivery. Low mileage and well maintained. Includes alternator, power steering pump, and AC compressor. No leaks, runs perfectly.',
		tags: ['j-series', 'vtec', 'v6', 'ridgeline', 'pilot', 'engine', 'j35'],
		image: ''
	},
	{
		id: '7',
		name: 'JDM Honda F20B VTEC Engine Accord Prelude 2.0L',
		price: 1899,
		category: 'Engine',
		condition: 'Excellent',
		model: 'Accord/Prelude',
		year: '1996-2001',
		mileage: 62000,
		shortDescription: 'F20B DOHC VTEC SiR-T engine',
		fullDescription: 'JDM Honda F20B 2.0L DOHC VTEC engine from Accord SiR-T. High-revving F-series with excellent power characteristics. Complete with intake manifold, throttle body, and all sensors. Popular swap for Accord and Prelude. VTEC engages smoothly. Clean engine with no modifications.',
		tags: ['f-series', 'vtec', 'accord', 'prelude', 'engine', 'f20', 'dohc'],
		image: ''
	},
	{
		id: '8',
		name: '2008-2012 Honda Accord Acura TSX K24A Engine IVTEC',
		price: 2100,
		category: 'Engine',
		condition: 'Excellent',
		model: 'Accord/TSX',
		year: '2008-2012',
		mileage: 45000,
		shortDescription: 'K24A i-VTEC 2.4L, very low miles',
		fullDescription: 'JDM Honda K24A i-VTEC engine from 2008-2012 Accord/TSX. 2.4L with advanced i-VTEC system. Extremely low mileage for the year. Complete with all accessories, coil packs, and sensors. Perfect for K-swap or direct replacement. Compression test shows excellent results. No leaks or issues.',
		tags: ['k-series', 'ivtec', 'accord', 'tsx', 'engine', 'k24', 'acura'],
		image: ''
	}
];
